# FROM node:16-alpine

# USER node

# # WORKDIR '/app'
# RUN mkdir -p /home/node/app
# WORKDIR /home/node/app

# # COPY package.json .
# # RUN npm install

# # COPY . .
# COPY --chown=node:node ./package.json ./
# RUN npm install
# COPY --chown=node:node ./ ./

# CMD ["npm", "run", "start"]
FROM node:alpine
 
USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
 
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
 
CMD ["npm", "start"]